var React = require('react');

var PresAddContent = React.createClass({ 
  render: function () {
    return (
    				<div className="mainContent">
							<h2>Presidential Welcome Address 2017</h2>
	    				<p>Dear Members of the Society for Free Radical Research International (SFRRI)</p>

							<p>I am extremely honored to represent our Society as the President and to follow and strengthen the philosophy and scientific contribution of the previous leading scientists who have served as President. In particular, I would like to give my special thanks and recognition to my immediate predecessor, Prof. Rafael Radi, for his leadership, commitment and the accomplishments of our Society during the past two years. Moreover, I would like to give many thanks for the contribution and work of all the other members of the executive and international committees, who have been essential in keeping our society running actively and soundly.</p>
						  <p>Some of you may be aware that I have been the President of the Society for Free Radical Research Japan (2015-18) and the Society for Free Radical Asia (2016-17), and that I have continuously interacted with free radical researchers from the different continents over more than 20 years. I am a pathologist and have been working on iron-induced carcinogenesis for many years. Yuji Naito and I have organized the 2014 Biennial SFRRI meeting in Kyoto, the ancient capital of Japan, which was attended by more than 600 participants with great success. Based now in Nagoya, Japan, I have greatly appreciated and encouraged international interactions over all these years, and I hope to continue to do so in my current role in the Society. Science is nowadays a highly globally-connected and integrated activity, and our Society serves to bridge concepts, people and events from different parts of the world, fostering a cohesive scientific organization built upon our regional societies, namely, Society for Free Redox Biology &amp; Medicine (SfRBM), Society for Free Radical Research Europe (SFRR Europe), Society for Free Radical Research Asia (SFRR Asia), Society for Free Radical Research Australasia (SFRR Australasia) and Society for Free Radical Research Africa (SFRR Africa). I believe that our international Society has played a role to keep us “together” as a worldwide scientific group. Among other actions, SFRRI has supported many international meetings in different areas of the world, including those with more recent scientific development, and participated in the international meetings, held jointly with one of the regional SFRR Societies.</p>
						  <p>The 2016 Biennial meeting, hosted and organized by Professor Neil Hogg, was a high quality meeting and in a most enjoyable venue (San Francisco, CA, USA) and appreciated hospitality. The meeting was attended by over 600 and was both scientifically and socially a quite remarkable experience. SFRRI is most thankful both to the organizers and also to the host Society (SfRBM). SFRR Europe will organize the next international meeting in the city of Lisbon, Portugal in July of 2018. We are looking forward to working together with SFRR Europe for the organization of this meeting, and I am very positive that this will be an outstanding and well-attended meeting, based on the science and also the attractive venue for this international conference.</p>
						  <p>The Society will continue providing support and, in some cases, guidance, for the organization and development of international free radical schools, courses, seminars, workshops and meetings in different parts of the world. We are experiencing a large number of requests to support meetings in different parts of the world, and while the Society can provide limited financial support, we will continue to do our best to help local organizers and will be also actively exploring ways that will lead to increase the funding opportunities.</p>
						  <p>I will maintain the three standing committees that Past President Rafael Radi has started in the areas of Education, Finances and Meetings/Outreach, comprised of members from our different regional societies. Specific requests from members wishing to serve on one of these committees will be advertised with regional societies shortly. In addition to the work on specific areas, these committees are likely to facilitate the promotion of young scientists into future leadership positions in our Society. Moreover, such committees will enhance the international interactions and provide an analysis of the different needs of regional societies that SFRRI represent.</p>
						  <p>We are committed to keep our Society scientifically sound. With the current explosion of redox biology content in extremely different areas of biomedical, pharmaceutical, agricultural and chemical research, we wish to highlight the importance of keeping our Society chemical species-oriented in addition to focusing on biomolecules and pathogenesis, a distinctive mark and strength of our organization since the very beginning of SFRRI. Thus, I trust that scientific programs and developments that involve our Society will be well balanced between mechanistic, quantitative and bioanalytical research and its application to understand human diseases with the aim of developing redox-based therapeutics. We are a prime example of organization with a niche opportunity for interdisciplinary research, including the integration of chemical, biochemical, cell and molecular biology and biomedical aspects.</p>
						  <p>Finally, I feel that in a rapidly changing world, SFRRI will continue to play an integral role in maintaining a platform for communicating sound science and to facilitate cultural exchanges, dialogue and understanding with scientists based in different parts of the world.</p>
						  <p>I hope that you continue to contribute to the development and success of SFRRI. Both the Executive Committee and I are very open to receive your suggestions and ideas!</p>
						 <p>Shinya Toyokuni</p>
						 <p>SFRRI President, 2017-2018</p>
						 <p>Professor, Nagoya University Graduate School of Medicine</p>
					 </div>
			    )
			  }
			});

module.exports = PresAddContent;